# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Paternagem
tagline:          'amor de pai'
description:      ' 

<br>

<br>
<div style="text-align: justify"> Espa√ßo para divulgar ideias e promover a paternagem de forma ativa, quebrando taboos e lutando pelos direitos dos pais que amam</div>'

url:              http://www.paternagem.com.br

author:
  name:           'Clarissa Becker'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/paternagem/paternagem.github.io
